project:
  type: website
  output-dir: docs

website:
  title: "The EV Foundation"
  open-graph: true
  google-analytics: G-P015KRTLYQ
  favicon: assets/faviconb.svg
  navbar: 
    logo: assets/faviconb.png
    background: primary
    left: 
        - text: "EV Tutorial"
          href: /tutorial
        - text: "EV Workshops"
          href: /workshops
        - text: "EV Day 2025"
          href: /evday2025
        - text: "Poker Camp"
          href: https://poker.camp
    right: 
      - text: "Fellows"
        href: fellows.qmd
      - text: "About"
        href: about.qmd
  sidebar:
    style: docked
    background: light
    contents: 
      - section: "EXPECTED VALUE"
        contents: 
          - text: Tutorial (soon)
          - href: evimp.qmd 
            text: EV Importance
          # - text: EV Benefits
          # - text: EV Flaws
      - section: "SPORTS"
        contents: 
          - text: Soon
      - section: "TRAVEL"
        contents: 
          - href: basicecon.qmd
            text: Basic Economy
      - section: "FOOD"
        contents: 
          - href: pizza.qmd
            text: Pizza
          - href: salmon.qmd
            text: Salmon
      - section: "GAMBLING"
        contents: 
          - href: dice.qmd
            text: Dice
          - href: dreidel.qmd
            text: Dreidel
          # - href: blackjack.qmd
          #   text: Blackjack
          # - href: gambler.qmd
          #   text: Gambler Problem
      - section: "CURRENT EVENTS"
        contents: 
          - href: huberman-pregnancy.qmd 
            text: Andrew Huberman Pregnancy Probability
          # - href: vice-president.qmd
          #   text: Vice President Selection
      - section: "OTHER"
        contents: 
          - href: hindsight-neglect.qmd
            text: LLM Hindsight Neglect

format:
  html:
    theme: flatly
    css: custom.css
    page-navigation: false
    bread-crumbs: false
    grid:
      sidebar-width: 260px
    math: true 
    html-math-method: katex
    toc: true
    toc-expand: true